// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	fxresponsefactory "github.com/ecumenos/ecumenos/internal/fxresponsefactory"

	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

type Factory_Expecter struct {
	mock *mock.Mock
}

func (_m *Factory) EXPECT() *Factory_Expecter {
	return &Factory_Expecter{mock: &_m.Mock}
}

// NewWriter provides a mock function with given fields: rw
func (_m *Factory) NewWriter(rw http.ResponseWriter) fxresponsefactory.Writer {
	ret := _m.Called(rw)

	if len(ret) == 0 {
		panic("no return value specified for NewWriter")
	}

	var r0 fxresponsefactory.Writer
	if rf, ok := ret.Get(0).(func(http.ResponseWriter) fxresponsefactory.Writer); ok {
		r0 = rf(rw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fxresponsefactory.Writer)
		}
	}

	return r0
}

// Factory_NewWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewWriter'
type Factory_NewWriter_Call struct {
	*mock.Call
}

// NewWriter is a helper method to define mock.On call
//   - rw http.ResponseWriter
func (_e *Factory_Expecter) NewWriter(rw interface{}) *Factory_NewWriter_Call {
	return &Factory_NewWriter_Call{Call: _e.mock.On("NewWriter", rw)}
}

func (_c *Factory_NewWriter_Call) Run(run func(rw http.ResponseWriter)) *Factory_NewWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter))
	})
	return _c
}

func (_c *Factory_NewWriter_Call) Return(_a0 fxresponsefactory.Writer) *Factory_NewWriter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Factory_NewWriter_Call) RunAndReturn(run func(http.ResponseWriter) fxresponsefactory.Writer) *Factory_NewWriter_Call {
	_c.Call.Return(run)
	return _c
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	mock := &Factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
