openapi: 3.0.1

info:
  title: Zookeeper API
  version: 0.1.0

servers:
  - url: "{{.ServerURL}}"

security:
- bearerAuth: []

components:
  schemas:
  securitySchemes:
    bearerAuth:
      $ref: "./shared-internal.yaml#/components/securitySchemes/bearerAuth"
