openapi: 3.0.1

info:
  title: Zookeeper Admin API
  version: 0.1.0

servers:
  - url: "{{.ServerURL}}"

security:
- bearerAuth: []

tags:
- description: Endpoints for interacting with Zookeeper Admin
  name: ZookeeperAdmin
- description: Endpoints for interacting with Authorization of Zookeeper Admin
  name: Authorization

paths:
  /sign-in:
    post:
      tags:
        - Authorization
      description: Sign in Zookeeper administrator.
      summary: Sign In
      operationId: signIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInRequest"
      responses:
        '200':
          description: Success
          headers:
            X-Request-Id:
              description: identifier of current request.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/RequestID"
            X-Request-Duration:
              description: duration of request processing in milliseconds.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/RequestDuration"
            X-Timestamp:
              description: timestamp of sending response.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/Timestamp"
            X-App-Version:
              description: app version is semver application version.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/SemverVersion"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "./shared-internal.yaml#/components/schemas/JSendResponseObject"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/SignInResponseData"
        '401':
          $ref: "./shared-internal.yaml#/components/responses/NotAuthorized"
        '403':
          $ref: "./shared-internal.yaml#/components/responses/Forbidden"
        '500':
          $ref: "./shared-internal.yaml#/components/responses/Error"
        default:
          $ref: "./shared-internal.yaml#/components/responses/Failure"
  /refresh-session:
    post:
      tags:
        - Authorization
      description: Refresh Zookeeper administrator's session.
      summary: Refresh Session
      operationId: refreshSession
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshSessionRequest"
      responses:
        '200':
          description: Success
          headers:
            X-Request-Id:
              description: identifier of current request.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/RequestID"
            X-Request-Duration:
              description: duration of request processing in milliseconds.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/RequestDuration"
            X-Timestamp:
              description: timestamp of sending response.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/Timestamp"
            X-App-Version:
              description: app version is semver application version.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/SemverVersion"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "./shared-internal.yaml#/components/schemas/JSendResponseObject"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/RefreshSessionResponseData"
        '401':
          $ref: "./shared-internal.yaml#/components/responses/NotAuthorized"
        '403':
          $ref: "./shared-internal.yaml#/components/responses/Forbidden"
        '500':
          $ref: "./shared-internal.yaml#/components/responses/Error"
        default:
          $ref: "./shared-internal.yaml#/components/responses/Failure"
  /sign-out:
    delete:
      tags:
        - Authorization
      description: Sign out Zookeeper administrator.
      summary: Sign Out
      operationId: signOut
      responses:
        '204':
          description: Session deleted successfully.
          headers:
            X-Request-Id:
              description: identifier of current request.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/RequestID"
            X-Request-Duration:
              description: duration of request processing in milliseconds.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/RequestDuration"
            X-Timestamp:
              description: timestamp of sending response.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/Timestamp"
            X-App-Version:
              description: app version is semver application version.
              schema:
                $ref: "./shared-internal.yaml#/components/schemas/SemverVersion"
      security:
        - bearerAuth: []  # Security requirement to specify that the endpoint requires authentication
      parameters: []  # No parameters in the path or query
      requestBody: {}  # No request body

components:
  schemas:
    Password:
      type: string
      format: password
      minLength: 8
      maxLength: 50
      pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).{8,}$'
    SignInRequest:
      type: object
      required:
        - email
        - password
      nullable: false
      properties:
        email:
          type: string
          format: email
        password:
          $ref: "#/components/schemas/Password"
    SignInResponseData:
      type: object
      required:
        - token
        - refresh_token
        - session_id
      nullable: false
      properties:
        token:
          type: string
        refresh_token:
          type: string
        session_id:
          type: integer
          format: int64
    RefreshSessionRequest:
      type: object
      required:
        - refresh_token
      nullable: false
      properties:
        refresh_token:
          type: string
    RefreshSessionResponseData:
      type: object
      required:
        - token
        - refresh_token
        - session_id
      nullable: false
      properties:
        token:
          type: string
        refresh_token:
          type: string
        session_id:
          type: integer
          format: int64

  securitySchemes:
    bearerAuth:
      $ref: "./shared-internal.yaml#/components/securitySchemes/bearerAuth"
